GET http://localhost:8000/api/v1/user

###
POST http://localhost:8000/api/v1/register
Content-Type: application/json 

{
    "email":"consduscstsssssssp11@gmail.com",
    "password": "12s3s45623"
}

###
POST http://localhost:8000/api/v1/login
Content-Type: application/json 

{
    "email":"conductp11@gmail.com",
    "password": "12345623"
}

